# generate this using secrets.token_urlsafe() or using pwgen(1)
flask-secret-key = '...'

# how many reverse proxies that add X-Forwarded-For headers is your site behind?
num-reverse-proxies = 1

# You can get your user id and password from
# su/baas/<guid>.dat in save folder 8000000000000010.

# Bytes 0x20 - 0x28 contain the user id as a single little endian integer,
# and bytes 0x28 - 0x50 contain the
# password in plain text.

# Alternatively, you can set up a mitm on your Switch
# and extract them from the request to /1.0.0/login

baas-user-id = 0x0123456789abcdef  # 16 hex digits
baas-password = "..."  # should be 40 characters

# Get this by mitming api.hac.lp1.acbaa.srv.nintendo.net/api/v1/auth_token on your Switch,
# at least until I find a better way

acnh-user-id = 0x0123456789abcdef  # 16 hex digits
acnh-password = "..."  # should be 64 characters

# this is the in game "creator ID" from the Designs Kiosk without hyphens or "MO"
acnh-design-creator-id = 1234_5678_9123

# You can dump prod.keys with Lockpick_RCM and
# PRODINFO from hekate (decrypt it if necessary)
keyset-path = "/path/to/prod.keys"
prodinfo-path = "/path/to/PRODINFO.img"

# Tickets can be dumped with nxdumptool.
# You need the base ticket, not an update ticket.
# Do not remove console specific data.
ticket-path = "/path/to/acnh-base.tik"

[postgres-db]
# keys are documented here: https://magicstack.github.io/asyncpg/current/api/index.html#asyncpg.connection.connect
# you'll probably want to configure at least "database", but all are optional
database = "acplaza"
